### ISSUE TITLE
Load a map

### ISSUE THREAD

**Issue by Pictar** [SojuJuseyo/Water-Drop-Map-Editor#10]
Read a JSON file and extract the map from it

**Comment by ThibaultHardin** [comment]
Ca marche bien, mais segfault si une map est incorrecte (j'ai mit le "20/20" en "20/"), ce serait bien d'avoir un p'tit message d'erreur pour pas perdre ce qu'on a sur l'editor si ça crash
Un autre truc, proposer de save le fichier avant d'en ouvrir un autre/quitter le programme si le truc actuel est pas enregistré du tout, ou si il est différent du dernier truc enregistré (tu compares avec l'emplacement de sauvegarde en mémoire si t'en as un)

**Comment by ThibaultHardin** [comment]
Le programme plante si la taille de la map est incorrect, dans le cas en dessous j'ai changé "30/30" en "30/3"

http://imgur.com/vMb9Foh

Solution peut-être : Tenter d'open dans un "cache" et ne remplacer la fenêtre actuelle que quand le load est complet et fonctionnel

**Comment by ThibaultHardin** [comment]
Changer "name" en "nam" dans le fichier fait planter le programme

**Comment by ThibaultHardin** [comment]
J'ai enlevé une accolade + virgule en random dans la tileListe, ça a fait planté le bail. Donc y'a toujours des segfault de caché. Vraiment je pense que ouvrir le truc "en cache" (ou en thread ou whatever) et que si ça marche a 100% alors le placer dans l'écran principal c'est la solution.

**Comment by Pictar** [comment]
Jpeux aussi try catch toute la fonction a ce rythme

**Comment by Pictar** [comment]
Envoie la map
