### ISSUE TITLE
Open a menu when the editor is launched

### ISSUE THREAD

**Issue by ThibaultHardin** [SojuJuseyo/Water-Drop-Map-Editor#13]

**Comment by ThibaultHardin** [comment]
When you open the editor it would be great to open a little window with just 2 buttons : "Create map" and "Open map", because right now when you start the editor you have to click on the top left of the window it's not the best we can have.

**Comment by Pictar** [comment]
It would be great that when we open the Map Editor it launches a little window with 2 buttons : "Create Map" and "Open Map" so that the user doesn't have to click on the top left button every time.
